# PLANNING
# Start with 3 lives each
# Lose a life if they answer a question wrong
# New question generated by picking numbers between 1 and 20
# Output scores at the end of each turn
# Announce winner at the end

# CLASSES THAT I WILL NEED
# Math Game
### Master class that generates the game
### Keeps state of who's turn it is

# Players
### Keeps track of the lives remaining of each player

# Questions
### Generate the random question that is prompted
### Know which player is answering the question